name: Build Zygisk Module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '34'
          build-tools: '34.0.0'
          ndk: '23.1.7779620'

      - name: Install CMake 3.22.1
        run: |
          yes | sdkmanager --install "cmake;3.22.1"
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "cmake.dir=$ANDROID_SDK_ROOT/cmake/3.22.1" >> local.properties

      - name: Grant Gradlew permission
        run: chmod +x ./gradlew

      - name: Build Release
        run: ./gradlew :module:assembleRelease --stacktrace

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zygisk-imgui-modmenu
          path: out/magisk_module_release/