name: Build Zygisk ImGui Menu

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Zygisk ImGui Menu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK & NDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '34'
          build-tools: '34.0.0'
          ndk: '26.1.10909125'

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew :app:assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zygisk-imgui-menu
          path: app/build/outputs/**/*.apk
          if-no-files-found: warn