name: Build Zygisk ImGui ModMenu

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK & NDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '34'
          build-tools: '34.0.0'
          ndk: '26.1.10909125'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build release
        run: ./gradlew :module:assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zygisk-imgui-modmenu
          path: out/magisk_module_release/
          if-no-files-found: warn